name: Update README
on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: Mabdou743
        run: node scripts/update-readme.js
      - name: Commit & Push (if changed)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README with latest repos
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
